// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpXRqf2w4C9LOjiMl63C2ttyqizbHijoY',
    appId: '1:808830825889:web:e05ad8784300da8bbb47e0',
    messagingSenderId: '808830825889',
    projectId: 'instagram-db02c',
    authDomain: 'instagram-db02c.firebaseapp.com',
    storageBucket: 'instagram-db02c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXI3atFAkCkOPalKU4IiiZamyq9MOCLgk',
    appId: '1:808830825889:android:fcfd5f60be105d89bb47e0',
    messagingSenderId: '808830825889',
    projectId: 'instagram-db02c',
    storageBucket: 'instagram-db02c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXsAzLmu7P5BDfuyY4MS23x6oseSTwBcM',
    appId: '1:808830825889:ios:8c6a12ac4e2d609fbb47e0',
    messagingSenderId: '808830825889',
    projectId: 'instagram-db02c',
    storageBucket: 'instagram-db02c.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXsAzLmu7P5BDfuyY4MS23x6oseSTwBcM',
    appId: '1:808830825889:ios:8c6a12ac4e2d609fbb47e0',
    messagingSenderId: '808830825889',
    projectId: 'instagram-db02c',
    storageBucket: 'instagram-db02c.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpXRqf2w4C9LOjiMl63C2ttyqizbHijoY',
    appId: '1:808830825889:web:7faab138f63a0bc3bb47e0',
    messagingSenderId: '808830825889',
    projectId: 'instagram-db02c',
    authDomain: 'instagram-db02c.firebaseapp.com',
    storageBucket: 'instagram-db02c.firebasestorage.app',
  );
}
